[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

# Removing the Next.js plugin since we're using static export
# [[plugins]]
#  package = "@netlify/plugin-nextjs"